### ISSUE TITLE
find_package(OpenCV) messes up the include paths in cost_map

### ISSUE THREAD

**Issue by bit-pirate** [stonier/cost_map#12]
Due to a bug in OpenCV's find package module (https://github.com/ros-infrastructure/bloom/issues/301) the order of the includes gets mixed up putting the debs before the sources. Hence compiling a newer version might fail, if one has the debs installed as well.

Probably this changes should go into [grid_map](https://github.com/yujinrobot/grid_map) as well.

Need to change the position of `find_package(OpenCV)` in [cost_map/CMakeLists.txt](https://github.com/stonier/cost_map/blob/indigo-devel/cost_map/CMakeLists.txt#L31).

**Comment by stonier** [comment]
Just tested...opencv doesn't mess up my paths. There is an interesting difference between my machine/jenkins and my old machine/yoru machine...the path list is different for some reason:

```
OPENCV_INCLUDE_DIRS............./usr/include/opencv;/usr/include
```

I am curious how the ros path gets in there...Nonetheless, because OpenCV does this badly, we should make it robust to problems caused by someone using a hand-installed opencv that might just happen to be in a bad location.

**Comment by stonier** [comment]
What is your `OpenCV_INCLUDE_DIRS`? Did you do a custom opencv install at any point? What version of opencv do you have?

**Comment by bit-pirate** [comment]
My `OpenCV_INCLUDE_DIRS`: `/opt/ros/indigo/include/opencv/opt/ros/indigo/include`

I'm not aware of any custom install. What I have on my system is OpenCV 2.4.

**Comment by bit-pirate** [comment]
Turned out the main cause of my struggles where an old installation of our custom OpenCV version, which pulled in the `/opt/ros/indigo` path. With the default version ((K)Ubuntu's OpenCV) the problems with ROS debs disappear, but there could still be a conflict with custom installs in `/usr/include`.

Feel free to close this one @stonier.

**Comment by stonier** [comment]
If we ever come back here again, just a note:

Important to make sure your `find_package(OpenCV)` comes **after** any `include_directories` you may have.
