### ISSUE TITLE
fromROSCostMap2D only works with sizes smaller than the actual size

### ISSUE THREAD

**Issue by AlexReimann** [stonier/cost_map#15]
E. g. trying to convert a 5 x 5 m ros costmap the length has to be a bit smaller than 5  x 5m, e. g. 4.9 x 4.9 m.

The error pops up [here](https://github.com/stonier/cost_map/blob/60a9585042e620a4df88388d0a42e46a18043e4d/cost_map/src/lib/converter.cpp#L386).

**Comment by AlexReimann** [comment]
Seems like the tf_pose.getOrigin() can't just be simply used but has to be adjusted to the map resolution (because the costmap align itself like that).

E. g. an tf origin of (-3.84537, -3.96554) has to become (-3.84, -3.96)

Also in general it would be good to be able to get just the whole map.

E. g. by requesting 0 or a negative size of the costmap.

**Comment by AlexReimann** [comment]
@stonier 
If you didn't see it yet

@bit-pirate 
fyi

**Comment by stonier** [comment]
Aye, I'm aware of it. Thanks for the issue.
