### ISSUE TITLE
Not building because unknown pkg geometry_msgs

### ISSUE THREAD

**Issue by AlexReimann** [stonier/cost_map#2]
Probably because of: https://github.com/ethz-asl/grid_map/pull/32

Seems like https://github.com/ethz-asl/grid_map is needed in the workspace for now.

**Comment by stonier** [comment]
They already have a [fix](https://github.com/ethz-asl/grid_map/pull/32) upstream, just not released yet. Closing this as it will eventually go away (we use a fork for now).
