### ISSUE TITLE
Implement toGridMap data copy or throw error

### ISSUE THREAD

**Issue by AlexReimann** [stonier/cost_map#20]
Or remove the function if it is not really implemented..
[This is evil](https://github.com/stonier/cost_map/blob/devel/cost_map/src/lib/converter.cpp#L313)

**Comment by stonier** [comment]
Something is using that, though I'd have to dig to find where. So yes - should absolutely copy over data fields, or have options on how things should be copied.

**Comment by stonier** [comment]
That link has moved on....the correct one is [cost_map/src/lib/converter.cpp@284f241](https://github.com/stonier/cost_map/blob/284f241c9ec7742ee8d278a2683f2f1dedb528ab/cost_map/src/lib/converter.cpp#L313)
