### ISSUE TITLE
cost_map_core build error

### ISSUE THREAD

**Issue by nitin5** [stonier/cost_map#45]
Hello 
Cost_map_core build is failing. cost_map::CostMap is referring elements which are not declared as members for this class.

cost_map_iterator.cpp:19:3: error: ‘mapIndexWithinRange’ is not a member of ‘grid_map’
   grid_map::mapIndexWithinRange(endIndex_, size_);
spiral_iterator.cpp:30:7: error: ‘checkIfIndexWithinRange’ is not a member of ‘grid_map’
   if (grid_map::checkIfIndexWithinRange(indexCenter_, bufferSize_)) pointsRing_.push_back(indexCenter_);
89:9: error: ‘checkIfIndexWithinRange’ is not a member of ‘grid_map’
     if (grid_map::checkIfIndexWithinRange(pointInMap, bufferSize_)) {
polygon_iterator.cpp:85:3: error: ‘limitPositionToRange’ is not a member of ‘grid_map’
   grid_map::limitPositionToRange(topLeft, mapLength_, mapPosition_);
polygon_iterator.cpp:86:3: error: ‘limitPositionToRange’ is not a member of ‘grid_map’
   grid_map::limitPositionToRange(bottomRight, mapLength_, mapPosition_);
circle_iterator.cpp:87:3: error: ‘limitPositionToRange’ is not a member of ‘grid_map’
   grid_map::limitPositionToRange(topLeft, mapLength_, mapPosition_);
circle_iterator.cpp:88:3: error: ‘limitPositionToRange’ is not a member of ‘grid_map’
   grid_map::limitPositionToRange(bottomRight, mapLength_, mapPosition_);

..........
..........
ellipse_iterator.cpp:95:3: error: ‘limitPositionToRange’ is not a member of ‘grid_map’
   grid_map::limitPositionToRange(bottomRight, mapLength_, mapPosition_);

**Comment by pfankhauser** [comment]
This is due to renaming changes in `grid_map_core`: https://github.com/ethz-asl/grid_map/commit/076a8b46fa193414b0cba4e8ebbebc730b032153#diff-46252e3b0e9495873facb5ed40daf9dc
@stonier Could you please adapt them in your code?

**Comment by stonier** [comment]
Thanks @pfankhauser. Sorry for the delay getting to it.
