### ISSUE TITLE
CostMap's getSubmap should be const

### ISSUE THREAD

**Issue by bit-pirate** [stonier/cost_map#6]
https://github.com/stonier/cost_map/blob/indigo-devel/cost_map_core/include/cost_map_core/CostMap.hpp#L287

and 

https://github.com/stonier/cost_map/blob/indigo-devel/cost_map_core/include/cost_map_core/CostMap.hpp#L299

It shouldn't change the object and without the const definition I cannot use it with a const object.

This would be a good change for grid_map as well, I guess.

**Comment by bit-pirate** [comment]
@stonier thoughts?

**Comment by stonier** [comment]
I agree...will test and throw them a PR. Did you already test?

**Comment by bit-pirate** [comment]
Created a PR for cost maps. Not sure if there is more needed.
